config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    resources :prescriptions, except: [:edit, :update, :destroy]
    resources :symptoms, except: [:edit, :update, :destroy]
  end
  resource :sessions, only: [:new, :create, :destroy]

end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :name, :date_issued

end

app/models/symptom.rb
class Symptom < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :name, :date_started
  validate :valid_date_ended

  private

  def valid_date_ended
    if (!date_ended.nil? && date_ended <= date_started)
      errors.add(:date_ended, 'Date Ended must be after Date Started')
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :email, :name, :password_digest, :date_of_birth
  validates_uniqueness_of :email
  has_secure_password
  has_many :prescriptions
  has_many :symptoms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_filter :load_user
  before_filter :authenticate
  rescue_from ActiveRecord::RecordNotFound, with: :handle_not_found

  def index
    @user = current_user
    @prescriptions = @user.prescriptions
    @new_prescription = @user.prescriptions.build
  end

  def create
    prescription = @user.prescriptions.build(prescription_params)
    if prescription.save
      redirect_to user_path(current_user), notice: 'Prescription added.'
    else
      flash[:now] = 'New Prescription Failed'
      render 'users/show'
    end
  end

  private
  def load_user
    @user = User.find(params[:user_id])
  end

  def handle_not_found
    redirect_to sessions_path, alert: 'Record Not Found'
  end

  def prescription_params
    params.require(:prescription).permit(:name, :date_issued)
  end

  def authenticate
    if @user != current_user
      redirect_to user_path(@user)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
   @user = User.find_by_email(params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: 'User Logged In'
    else
      flash.now[:error] = 'Invalid Username/Password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_sessions_path, notice: 'Logged Out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :handle_not_found
  before_action

  def show
    @user = User.find(params[:id])
    handle_not_found if @user != current_user
    @new_prescription = @user.prescriptions.build
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      flash.now[:error] = 'User could not be created.'
      render :new
    end
  end

  private

  def handle_not_found
    redirect_to user_path(current_user), alert: 'User Not Found'
  end

  def user_params
    params.require(:user).permit(:name, :email, :date_of_birth, :gender, :password, :password_confirmation)
  end

  def authorize
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthTrack</title>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css', media: 'all' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row">
    <header class="col-md-12">
      <h1>HealthTrack
        <small><%= yield :title %></small>
      </h1>
    </header>
  </div>

  <% unless flash.empty? %>
      <div class="row">
        <div class="col-md-12">
          <% if flash.notice %>
              <div class="alert alert-info">
                <%= flash.notice %>
              </div>
          <% end %></div>
        <div class="col-md-12">
          <% if flash.alert %>
              <div class="alert alert-danger">
                <%= flash.alert %>
              </div>
          <% end %></div>
      </div>
  <% end %>

  <div class="row">
    <div class="col-md-3">
      <% if current_user %>
          <div class="row">
            <%= content_tag :div, "Welcome #{current_user.name}", class: 'col-md-12' %>
          </div>
      <% end %>
      <nav class="row">
        <div class="col-md-12">
          <div class="list-group">
            <% if current_user %>
                <%= link_to 'Prescriptions', user_prescriptions_path, class: 'list-group-item' %>
                <%= link_to 'Symptoms', user_symptoms_path, class: 'list-group-item' %>
                <%= link_to 'Log Out', sessions_path, method: :delete, class: 'list-group-item' %>
            <% else %>
                <%= link_to 'Create User', new_user_path, class: 'list-group-item' %>
                <%= link_to 'Log In', new_sessions_path, class: 'list-group-item' %>
            <% end %>
          </div>
        </div>
      </nav>
      <div class="row">

      </div>
    </div>
    <div class="col-md-9">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/prescriptions/_prescription.html.erb
<% unless prescription.id.nil? %>
    <div class="col-md-12">
      <%= prescription.name %>&ndash; <%= prescription.date_issued.to_formatted_s(:short) %>
    </div>
<% end %>

app/views/prescriptions/index.html.erb
<% content_for :title do %>User History
<% end %>
<section class="row">
  <div class="col-md-12">
    <%= current_user.name %> &ndash; <%= @user.date_of_birth.to_formatted_s(:short) %> &ndash; <%= @user.gender %>
  </div>
</section>
<section class="row">
  <div class="col-md-12"><h2>Medication History</h2></div>
  <% if @prescriptions.count == 0 %>
      <div class="col-md-12">
        <div class="alert alert-warning">No Prescriptions</div>
      </div>
  <% else %>
      <%= render @prescriptions %>
  <% end %>


  <div class="col-md-12"><%= form_for([@user, @new_prescription]) do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :date_issued %>
          <%= f.date_field :date_issued, class: 'form-control' %>
        </div>
        <%= f.submit %>
    <% end %></div>

</section>

app/views/users/_user_form.html.erb
<%= form_for(@user, html: {class: 'form-horizontal'}) do |f| %>
    <% if @user.errors.any? %>
        <div class="row">
          <div class="col-md-12">
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>
    <div class="form-group">
      <%= label @user, :name, class: 'control-label col-md-3' %>
      <%= content_tag(:div, (f.text_field :name, class: 'form-control'), class: 'col-md-9') %>
    </div>
    <div class="form-group">
      <%= label @user, :email, class: 'control-label col-md-3' %>
      <%= content_tag(:div, (f.text_field :email, class: 'form-control'), class: 'col-md-9') %>
    </div>
    <div class="form-group">
      <%= label @user, :password, class: 'control-label col-md-3' %>
      <%= content_tag(:div, (f.password_field :password, class: 'form-control'), class: 'col-md-9') %>
    </div>
    <div class="form-group">
      <%= label @user, :password_confirmation, class: 'control-label col-md-3' %>
      <%= content_tag(:div, (f.password_field :password_confirmation, class: 'form-control'), class: 'col-md-9') %>
    </div>
    <div class="form-group">
      <%= label @user, :date_of_birth, class: 'control-label col-md-3' %>
      <%= content_tag(:div, (f.date_field :date_of_birth, class: 'form-control'), class: 'col-md-9') %>
    </div>
    <div class="form-group">
      <%= label @user, :gender, class: 'control-label col-md-3' %>
      <div class="col-md-6">
        <%= f.radio_button(:gender, 'M') %> <span>Male</span>
        <%= f.radio_button(:gender, 'F') %> <span>Female</span>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-12">
        <%= f.submit %>
      </div>
    </div>
<% end %>

app/views/users/new.html.erb
<%= render 'user_form' %>

app/views/users/show.html.erb
<% content_for :title do %>User History
<% end %>
<section class="row">
  <div class="col-md-12">
    <%= @user.name %> &ndash; <%= @user.date_of_birth.to_formatted_s(:short) %> &ndash; <%= @user.gender %>
  </div>
</section>
<section class="row">
  <div class="col-md-12"><h2>Medication History</h2></div>
  <% if @user.prescriptions.count == 0 %>
      <div class="col-md-12">
        <div class="alert alert-warning">No Prescriptions</div>
      </div>
  <% else %>
      <% @user.prescriptions.each do |prescription| %>
          <% unless prescription.id.nil? %>
              <div class="col-md-12">
                <%= prescription.name %>&ndash; <%= prescription.date_issued.to_formatted_s(:short) %>
              </div>
          <% end %>
      <% end %>
  <% end %>


    <div class="col-md-12"><%= form_for([@user, @new_prescription]) do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :date_issued %>
          <%= f.date_field :date_issued, class: 'form-control' %>
        </div>
        <%= f.submit %>
    <% end %></div>

</section>